package io.zicteam.zeconomy.api.model;

public enum ApiErrorCode {
    NONE,
    SERVER_UNAVAILABLE,
    PLAYER_NOT_FOUND,
    PLAYER_OFFLINE,
    CURRENCY_NOT_FOUND,
    INVALID_AMOUNT,
    INVALID_PIN,
    INSUFFICIENT_FUNDS,
    TREASURY_INSUFFICIENT_FUNDS,
    RATE_NOT_FOUND,
    FEATURE_DISABLED,
    VAULT_UNAVAILABLE,
    OPERATION_FAILED
}
